// deno-fmt-ignore-file
// biome-ignore format: generated types do not need formatting
// prettier-ignore
import type { PathsForPages } from 'waku/router'

// prettier-ignore
type Page =
  | { path: '/getting-started'; render: 'static' }
  | { path: '/guides/coordinates'; render: 'static' }
  | { path: '/guides/crawler-client'; render: 'static' }
  | { path: '/guides/onchain'; render: 'static' }
  | { path: '/guides/react'; render: 'static' }
  | { path: '/guides/worlds-and-views'; render: 'static' }
  | { path: '/'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/classes/ClientChainMismatchError'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/classes/InvalidTokenMetadataError'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/classes/MissingAssemblerError'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/classes/UnknownContractError'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/classes/UnsupportedChainError'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/assembleEcTokenPayload'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/assembleTokenPayload'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/formatViewData'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getAllContractNames'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getCardsContract'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getContractAbi'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getErc20'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getErc721'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getPublicClient'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getTypedContract'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/getWorldContract'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/readOwnerOf'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/readTokenMetadata'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/readTotalSupply'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/resolveClient'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/functions/watchMints'; render: 'static' }
  | { path: '/reference/@avante/crawler-api'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/AssembledEcAttribute'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/AssembledEcChamber'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/AssembledEcMetadata'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/AssembledEcTokenPayload'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/BoundContractOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/ContractOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/ReadOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/TokenMetadata'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/TypedContractOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/interfaces/WatchMintsOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/type-aliases/AssembledTokenPayload'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/type-aliases/KnownContractName'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/type-aliases/OnMint'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/type-aliases/TypedContract'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/variables/contractAbis'; render: 'static' }
  | { path: '/reference/@avante/crawler-api/variables/defaultWatchIntervalMs'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/AmbiguousWorldError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/Chamber'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/Crawler'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/DuplicateWorldError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/MissingConverterError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/MissingViewError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/UnknownWorldError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/WorldHandle'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/classes/WorldValidationError'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/enumerations/Dir'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/enumerations/Gem'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/enumerations/Terrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/enumerations/TileType'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/compassToCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/compassToSlug'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/coordToCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/coordToSlug'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/createCrawler'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/findTilesInTilemap'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/flipDir'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/flipDoorPosition'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getChamber'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getChamberByTokenId'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getChamberCount'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getChambers'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getChambersByCoords'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getCoordinateSchema'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getDoorsTo'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getDynamicChamberCoords'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getDynamicChamberCount'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getDynamicChamberTokenIds'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getInvalidatedCoords'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getOppositeTerrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getSchema'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getStaticChamberCount'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getTokenCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getTokenCount'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getTokenIds'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getTokenSvg'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/getWorldInfo'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/hasView'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/isSchemaName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/isTile'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/loadWorld'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/mergeConvertedToken'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/minifyNewsCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/neighborCoords'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/newsCompassEquals'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/offsetCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/offsetNewsCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/resolveCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/slugToCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/slugToCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/tileToXy'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/toTilemap'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/validateCoord'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/validateNewsCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/validateSlug'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/validatedNewsCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/functions/xyToTile'; render: 'static' }
  | { path: '/reference/@avante/crawler-core'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/ChamberData'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/ChamberDataJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/ChamberIdLibrary'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/ChamberLocator'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/ConvertedToken'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/Converter'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/CoordinateSchemaLibraries'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/CoordinateSchemaLibrary'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/DataSchema'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/Door'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/DoorJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/Hoard'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/NewsLibrary'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/TilemapSize'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/World'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldBundle'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldInfo'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldInfoJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldUpdatedEvent'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/WorldViews'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/interfaces/Xy'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/AttributeSpec'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/AttributeValueOf'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/AttributesOf'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/BigIntJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ChamberCC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ChamberDataCC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ChamberDataEC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ChamberEC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ChamberSize'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/CncAttributes'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/CncTerrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/Compass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/CompassJson'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ContractName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/CoordinateLibraryOf'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/CoordinateSchemaName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/EcAttributes'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/EcGemType'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/EcTerrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/InvalidationPolicy'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/Network'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/NewsCompass'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/NewsCompassDir'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/NewsCompassInput'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/SchemaName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/SchemaViewName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/SlugSeparator'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/TerrainOf'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/Tile'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/Tilemap'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/TilemapIsh'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/ViewName'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/WorldHandleCC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/WorldHandleEC'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/WorldSource'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/type-aliases/WorldUpdatedListener'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/CoordMask'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/CoordMax'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/CoordOffset'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/CoordOne'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/DirNames'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/FlippedDir'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/GemNames'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/OppositeTerrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/TerrainNames'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/chamberId'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/cnc'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/defaultSlugSeparator'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/ec'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/ecGemFromChain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/ecTerrainFromChain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/news'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/oppositeEcTerrain'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/schemas'; render: 'static' }
  | { path: '/reference/@avante/crawler-core/variables/slugSeparators'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/classes/TokenConversionError'; render: 'static' }
  | { path: '/reference/@avante/crawler-data'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/interfaces/EcChamberMetadata'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/interfaces/EcChamberStruct'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/interfaces/EcTokenAttribute'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/interfaces/EcTokenMetadata'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/interfaces/EcTokenPayload'; render: 'static' }
  | { path: '/reference/@avante/crawler-data/variables/ecConverter'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/classes/CrawlerApiUnavailableError'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/ChamberSvg'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/CrawlerProvider'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useChamber'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useChamberEC'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useChamberNeighbors'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useChamberSchema'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useChambers'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useCrawler'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useTokenSvg'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorld'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorldEC'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorldInfo'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorldNames'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorldSchema'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/functions/useWorldSelector'; render: 'static' }
  | { path: '/reference/@avante/crawler-react'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/interfaces/ChamberNeighbor'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/interfaces/ChamberSvgProps'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/interfaces/CrawlerProviderProps'; render: 'static' }
  | { path: '/reference/@avante/crawler-react/interfaces/LiveUpdateOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/classes/InvalidBigIntishError'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/equals'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/fromBinaryArray'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/isBigInt'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/isBigIntish'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/isHexString'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toAddress'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toBigInt'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toByteArray'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toDecimalString'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toHex'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/functions/toNumberArray'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/type-aliases/BigIntish'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/bi/type-aliases/HexString'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/functions/decodeBase64'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/functions/decodeBase64Text'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/functions/decodeDataUri'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/functions/encodeBase64'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/functions/encodeDataUri'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/encode/interfaces/EncodeDataUriOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format/functions/deserialize'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format/functions/formatJSON'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format/functions/formatXML'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format/functions/serialize'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/format/interfaces/FormatXmlOptions'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/seeder/functions/makeSeed'; render: 'static' }
  | { path: '/reference/@avante/crawler-utils/seeder'; render: 'static' }
  | { path: '/reference'; render: 'static' }

// prettier-ignore
declare module 'waku/router' {
  interface RouteConfig {
    paths: PathsForPages<Page>
  }
  interface CreatePagesConfig {
    pages: Page
  }
}
