/**
 * ABI codegen (SDK-refactor P3 — see specs/SDK_SPECS.md §`crawler-api`).
 *
 * Derives const-asserted TS ABIs from the committed artifact JSON
 * (`src/artifacts/*.json` — the single source of truth) into the generated,
 * git-ignored `src/generated/abis.ts`. viem's type inference requires literal
 * types, which JSON imports cannot carry — never hand-write or commit the TS
 * form. Only the `abi` arrays are emitted; the artifact `networks` address
 * tables never enter the output (addresses come from the world binding or the
 * caller).
 *
 * Runs via the package's `gen` script, which every compile/type-check/test
 * path executes first — a fresh clone needs no manual step.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const artifactsDir = join(packageDir, 'src', 'artifacts');
const outFile = join(packageDir, 'src', 'generated', 'abis.ts');

interface Artifact {
  contractName: string;
  abi: unknown[];
}

const files = readdirSync(artifactsDir)
  .filter((file) => file.endsWith('.json'))
  .sort();

const artifacts: Artifact[] = files.map((file) => {
  const { contractName, abi } = JSON.parse(readFileSync(join(artifactsDir, file), 'utf8'));
  if (typeof contractName !== 'string' || !Array.isArray(abi)) {
    throw new Error(`generateAbis: artifact [${file}] has no contractName/abi`);
  }
  return { contractName, abi };
});

const constName = (contractName: string): string =>
  `${contractName[0].toLowerCase()}${contractName.slice(1)}Abi`;

const lines: string[] = [
  '// Generated by scripts/generateAbis.ts — DO NOT EDIT.',
  '// Source of truth: src/artifacts/*.json (abi arrays only; networks tables never enter).',
  "import type { Abi } from 'viem';",
  '',
];

for (const { contractName, abi } of artifacts) {
  lines.push(
    `export const ${constName(contractName)} = ${JSON.stringify(abi)} as const satisfies Abi;`,
    '',
  );
}

lines.push(
  '/** every bundled contract ABI, keyed by contract name */',
  'export const contractAbis = {',
  ...artifacts.map(({ contractName }) => `  ${contractName}: ${constName(contractName)},`),
  '} as const;',
  '',
);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join('\n'));
console.log(`generateAbis: ${artifacts.length} ABIs → src/generated/abis.ts`);
