/**
 * The `ec` token payload — the converter's input shape (SPECS §Data pipeline
 * item 2), typed from the real cached tokenURI JSON produced by the P4 cache.
 *
 * Everything the converter needs is inside `metadata`: the readable tokenURI
 * attributes plus the embedded on-chain `chamber` struct (the SVG alone does not
 * carry the full map data). Field types are `BigIntish` where the cached JSON
 * (numbers / decimal strings) and a live viem-decoded struct (`bigint`s) differ —
 * both assemble into the same payload without conversion.
 */
import type { BigIntish, HexString } from '@avante/crawler-core';

/** One OpenSea-style trait of the cached tokenURI metadata — values are readable strings. */
export interface EcTokenAttribute {
  readonly trait_type: string;
  readonly value: string;
}

/**
 * The cached tokenURI metadata JSON, blob fields extracted (`image` → the payload
 * `svg`; `animation_url` → the cache's `.html`, never part of the payload).
 */
export interface EcTokenMetadata {
  /** the chamber's display name (`'Chamber #1'`) — becomes `ChamberData.name` */
  readonly name: string;
  readonly description?: string;
  readonly external_url?: string;
  readonly background_color?: string;
  /** the readable traits: Chapter, Terrain, Coordinate, Yonder, Gem, Coins, Worth + compass directions */
  readonly attributes: readonly EcTokenAttribute[];
}

/**
 * The raw on-chain `Crawl.ChamberData` struct, as archived by the cache (embedded
 * in each token's `.json` as `chamber`) or decoded live by viem. Chain-scale
 * values are `BigIntish`; `tilemap` is the generated byte string.
 */
export interface EcChamberStruct {
  readonly coord: BigIntish;
  readonly tokenId: BigIntish;
  readonly seed: BigIntish;
  readonly yonder: BigIntish;
  readonly chapter: number;
  /** chain terrain value (`Crawl.Terrain`) */
  readonly terrain: number;
  /** chain direction value (`Crawl.Dir`) of the chamber's entry door */
  readonly entryDir: number;
  readonly hoard: {
    /** chain gem value (`Crawl.Gem`) */
    readonly gemType: number;
    readonly coins: number;
    readonly worth: number;
  };
  readonly gemPos: number;
  /** door tile positions in NEWS order — `0` = no door on that edge */
  readonly doors: readonly number[];
  /** lock status in NEWS order (`0`/`1`) — parallel to `doors` */
  readonly locks: readonly number[];
  /** legacy packed path map — unused (the tilemap is the only map representation) */
  readonly bitmap?: BigIntish;
  /** the generated tile bytes (one tile per byte, row-major, leading zero bytes meaningful) */
  readonly tilemap: HexString;
  readonly customData?: readonly unknown[];
}

/**
 * The embedded on-chain struct, exactly as the cache stores it in the token JSON —
 * named `chamber` (not `chamberData`: the `chamberData` *view* holds the converted
 * shape, which differs).
 */
export interface EcChamberMetadata {
  readonly chamber: EcChamberStruct;
}

/**
 * The `ec` converter's input for one token (SPECS §Data pipeline item 2):
 * the cached tokenURI JSON intersected with the embedded on-chain struct, plus the
 * decoded original SVG — which is display-only (`tokenSvg` view) and never parsed.
 */
export interface EcTokenPayload {
  readonly tokenId: BigIntish;
  /** the cached tokenURI JSON (blob fields extracted) + the embedded `{ chamber }` struct */
  readonly metadata: EcTokenMetadata & EcChamberMetadata;
  /** the decoded original SVG — passed through untouched for the `tokenSvg` view */
  readonly svg: string;
}
